### ISSUE TITLE
Requests can be empty

### ISSUE THREAD

**Issue by surfaace** [drftpd-ng/drftpd3#24]
It seems that you can request empty requests, need to be checked if its from IRC or site ftp

(10:57:28) [1]     site requests
(10:57:28) [1] 200- REQUESTS:
(10:57:28) [1] 200- [4]  by someone

**Comment by Scitz0** [comment]
I did some testing on this and just typing site request and nothing more does not let you make an empty request. Doesn't matter if you add spaces to the end. Tried both on IRC and FTP.

However, you can fool the master if you like. I found two ways to create and empty request.

First one is to type site request and then ALT+255, this creates a space character that the system thinks is a valid request but messes up VFS to be honest. You wont be able to delete request or the directory after this. You have to shut master down and remove dir from VFS in master files/ dir. 
This might be a general VFS issue and not related to just REQUEST, ie MKD might behave the same way, not tested.

The second is to manually create a dir with the format REQUEST-by.nick- in the REQUEST dir.
This will list an empty item.

**Comment by Scitz0** [comment]
Fixed in dd94b2c10b20b10f7e4fd7f98eade2e86109ca64
The default conf setting added to request.conf now denies stuff like ALT+255.
I was unable to replicate the error now.
The possibility to manually create the request dir is still there but thats up to the end user to limit this in perms.conf if needed.
