### ISSUE TITLE
MySQL usermanager plugin

### ISSUE THREAD

**Issue by cmstest** [drftpd-ng/drftpd3#25]
I thought about creating a mysql usermanager plugin (based on org.drftpd.usermanager.encryptedjavabeans) so that we could use mysql databases for user handling too.

What do you think about this? Any ideas on how to implement it or do you have any better ideas?

**Comment by Scitz0** [comment]
I dont think a database is the answer for many reasons. Its very hard to design the database structure with the user data being dynamic and extendable. And to use a database for only user storage seems excessive as its only used when loading users at start and when writing changes to the user.

What would a database solution give that the xml solution doesn't provide today?

**Comment by cmstest** [comment]
It makes it easier to hook up a website to it and add users on the fly, without having to deal with xml files and modifying them. We've got a drftpd running inhouse and it would make all of our lifes easier if we could just hook it up to a database and let our internal scripts fill the database with the users from different systems. That's how I got to this idea :)
While using XMLs we'd have to ssh to the server or build an internal script that modifies the xml files and saves them and that would be quite a bigger task than using an sql database.

**Comment by EHCanadian** [comment]
Build your own database structure as you need it for your records.
Most commands can be executed using built in language functions.

So say UserA is assigned to drftpd_site_id =1
You would use the drftpd account to login using the build in ftp function library via ftp
and execute them changes. Then you basically got to write the web end for what you wanted to
do anyhow so it allows you to customize your data structure.

All the plugins would have to be re-written to use the MySQL aspect and since drftpd is a niche software
you likely are not going to get the support of the initial creators of whatever plugins you use. 

Sure some configurations will have to be initially setup such as slave selections, group permissions and such and trying to add MySQL to support all that is a complete rewrite. But my guess is this is already done and you got some user accounts that should be obeying by some define rules.

Maybe you run a leech site and you are selling bandwidth credits. I get it. But this is only going to work
for you to remove the manual task of altering accounts. Depending on how much "custom" services you offer to your clients/users depends on the http end that you will spend time on.. I did a java source edit to allow the siteop to view passwords in plain text before hand. While this is not longer needed as I store that info into a private database structure I have done myself for my needs when end users forgot their login info.

I agree with Scitz0 as you don't really have to edit the xml file directly as most mods or build in functions
are capable of returning 250 responses that you can parse to see if any 500 errors have occurred. 

For editing user accounts the best way is to make your own functions and execute them though the coding language of your choosing. I myself have already done this for my specific needs so I'm not
trying to be a @ss about this.

Its the only way you are going to be able to automate user management over your drftpd services

Don't mean to bring up a old issue. Just offering what likely you will have to do or have already done.

**Comment by zc0nf** [comment]
This request will not be implemented (not requested enough)
