### ISSUE TITLE
Problem Mediainfo .avi 

### ISSUE THREAD

**Issue by bibidinu** [drftpd-ng/drftpd3#71]
I'm using the latest development
When I try to put sample xvid .avi
Slave goes offline And does not go until you delete the .avi file

log di errore è qui 
https://pastebin.com/KfD0jZY4
Checking with mediainfo shell error 3.77 refers to the File size

File_size : 3.77 MiB

**Comment by zer0c0nf** [comment]
This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by bibidinu** [comment]
zer0c0nf i have reup another .log with another file 

https://pastebin.com/4YJ3TKgk

**Comment by bibidinu** [comment]
Some News about this bug?

**Comment by Scitz0** [comment]
According to log it happens when trying to convert the field "File size" from mediainfo output. This is then sent to another class in DR to convert this string info actual bytes DR can handle. This is where it fails, this byte conversion Bytes.parseBytes() is using Long object to convert value, and Long do not support fractions. 

I guess the best approach would be to change the general parseBytes method to handle fractions correctly.

**Comment by Scitz0** [comment]
Fixed in 6c98bd7c6d64c8cc67997fdfe315576f589d7667

**Comment by bibidinu** [comment]
Great job! Thanks @Scitz0
